version: "3"
services:

  db:
    image: mymysqlimg:1.0
    networks:
      - backend
    container_name: mysqldb
  tomcat:
    depends_on:
      - db
    image: mytomcatimg:1.2
    networks:
      - backend
    ports:
      - "80:8080"

networks:
  backend:
    driver: bridge